# require the branch name to be release (note for PRs this is the base branch name)
language: go
go:
  - "1.13"
os: linux
dist: xenial
install:
  # - go get -v github.com/comp500/packwiz
  - echo 'lol install :)'
script:
  - echo "lol script :)"
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Henry Post"
  - git config --local user.email "HenryFBP@gmail.com"
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export VERSION_TAG="`cat VERSION`"
  - echo "$VERSION_TAG" > VERSION_TAG
  - git tag -l --contains HEAD > HEAD_TAG

  - echo "Version tag - `cat VERSION_TAG`"
  - echo "Latest commit's tag - `cat HEAD_TAG`"
  
  # Make sure the tag of the most recent commit is the same as the file...
  - >
    if cmp -s "VERSION_TAG" "HEAD_TAG"; then
      printf 'Last commit was tagged correctly.'
    else
      printf 'Last commit was not tagged correctly. It does not match.'
    fi

  - echo "Releasing RoI ${VERSION_TAG}..."
  # - git tag "${VERSION_TAG}" # user does this themselves now...

  - git clone https://github.com/comp500/packwiz
  - pushd packwiz
  - go install .
  - popd

  - packwiz refresh
  - packwiz cf export
  - mv export.zip "rivers-of-iron-release-${VERSION_TAG}.zip"
  - ls -lash
deploy:
  provider: releases
  api_key:
    secure: "AozltCNsfBqf8uC/MasoLd97BgTqjJmLo60eM5PIwFwcEqe4PAr9uJg2gPheus2M9WDrANgBtAPKcc0TjLOqKNlHe3/Js4qD8VN5RplEfJVGQi2rjrFDfFMq+rk/UG1mfeUtE1kNofCbNXrHSMUo32ZGd4MITOrmCSLx8HyPkwMahJjdxClrEGv2AQQR0LvjJxKQdhbpiU+okSNLj2AAKUWLU/6iqC13DpT7Ppq50i521dr1URQPh8Kx9AeG/fYzL5081G7/YlOGJeuU16ft3sUdN4UzF7XynPR4kaJpO6ZUNJ2tn7hwRw4RZBwEY1HhxviqCAq8xhBKtVdpdbKrnkj33ZfTWDNjDfh9wloHZLBUQUHzKo6mi1O9SGhmeoXXVNNdNzKrZkDHgG94T548wFPccNF3vOAFrYFR8RAev5IIPTkY5WSexEbNjr8yDYYwqBGhRhuBKsRAZ2hb1FenYpetVfM6/0t/5dFPkcamXZFBzsjp4gu0+E3WFd0wt15kcCkL65rkd9EDm0CFzVZFHo3K8iQMVIyXlTRvHktGh7f4ZuwULcqU3eVC7FWeg8cRHpo781sVt7nc6L6ZC38z9382n1OXg7sc0H0GLCGf8jpemAnJvFaQjLOHYvRkyBhOCAQW4YvRFFjyk6P75gGIrp0AYFPHkKAjkeMNRnvgA3s="
  file:
    - "rivers-of-iron-release-${VERSION_TAG}.zip" #todo not this file, export.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: HenryFBP/rivers-of-iron-mc
    branch: release
