# require the branch name to be release (note for PRs this is the base branch name)
language: go
go:
  - "1.13"
os: linux
dist: xenial
install:
  # - go get -v github.com/comp500/packwiz
  - echo 'lol install :)'
script:
  - echo "lol script :)"
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Henry Post"
  - git config --local user.email "HenryFBP@gmail.com"
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - export VERSION_FILE_CONTENT="`cat VERSION`"
  - echo "$VERSION_FILE_CONTENT" > VERSION_FILE_CONTENT
  - git tag -l --contains HEAD > HEAD_TAG

  - echo "Version file content - `cat VERSION_FILE_CONTENT`"
  - echo "Latest commit's tag - `cat HEAD_TAG`"
  
  # Make sure the tag of the most recent commit is the same as the file...
  - |
    if cmp -s "VERSION_FILE_CONTENT" "HEAD_TAG"; then
      echo 'Last commit was tagged correctly.'
    else
      echo 'Last commit was not tagged correctly. It does not match.'
      exit 1
    fi

  - echo "Releasing RoI ${VERSION_FILE_CONTENT}..."
  # - git tag "${VERSION_FILE_CONTENT}" # user does this themselves now...

  - git clone https://github.com/comp500/packwiz
  - pushd packwiz
  - go install .
  - popd

  - packwiz refresh
  - packwiz cf export
  - mv export.zip "rivers-of-iron-release-${VERSION_FILE_CONTENT}.zip"
  - ls -lash
deploy:
  provider: releases
  api_key:
    secure: "Cjpv3RqmbK/5EYzPhFPI4pitY3l5FMYDUJWLul89mQzcH1YC7mtxwDhX0Wb4jCQf5cXgyT1AkoLvueMZMxjAV5FFpGjRhiGamI3H51yo2nBB0lV2Ic8ckuQi0/gcoKVReN0nFFc90nNuIHEdyczfHMmyd7K/GROig1vOfM+NPyyezRrDs8sy9WhkyWUIZsYJSFegWSJtdldLCZc6KMtDDpUz7sNM7oL/js/pPNIR7AdVCDqMSS+lL5arifA+duuKcECd1C7dQRK9kTchdHl2Qvw4MAT9V4PIdI4JI/UewOYQCQ246BL2YXlQkMnJR5DiYOsU7rt4qvJzmcghwN5bGDPZRpg05HUfk345oYdt5MulPKG8ddBqwM+XXCimANSCV59GF/ZnmSz6A0VYA72njSybdFOBjUmMr0/GOPIHBAYLr8YxE0SWhm0fsYdK72Oyj2dPEkYR6NS6fh2HzrFRm/LOztPK4SVNvGHDtdZ8rKsiFD6wzKcCWkmrkNASJrNI+AaIzYrrw4UtSgs3ZoBluuonrrnq8RaapAkAFGygDi+lTP0y3AbxjYw7Fjk9Veu2HYVpsdVkxG8z4i8Hyhhce6Yz7UOYfXUi0JzwvsD6xUYRlhYHHn9cCzqgCwkA/zLhXAW/Lk5Kz1Kr3HgqPLlLP67KqFA1DeRa7/PVrKiik+4="
  file:
    - "rivers-of-iron-release-${VERSION_FILE_CONTENT}.zip" #todo not this file, export.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: HenryFBP/rivers-of-iron-mc
    branch: release
