name = "Rivers of Iron"
author = "HenryFBP"
version = "v1.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa4220d6e4dbaa347ff59b5f42b76664d5c3ca1ddab31ca821e59f6b4e4350a"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
