name = "Rivers of Iron"
author = "HenryFBP"
version = "v1.1.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44867be42d2071b53d190a603fec383da796bb04c7dab7a632dcc602c0d0b63b"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
