name = "Rivers of Iron"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7244d64eed1be2c20a44cffafdea7ed32a2eb56f6d765ccbcc2ff05ddb0002bc"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
