name = "ActuallyComputers"
filename = "actuallycomputers-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3083/325/actuallycomputers-2.2.0.jar"
hash-format = "murmur2"
hash = "3691297459"

[update]
[update.curseforge]
file-id = 3083325
project-id = 253005
release-channel = "beta"
