name = "Armor Underwear Mod [FORGE]"
filename = "armorunder-mc1.12.2-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2660/325/armorunder-mc1.12.2-1.0.0.jar"
hash-format = "murmur2"
hash = "2913180219"

[update]
[update.curseforge]
file-id = 2660325
project-id = 310383
release-channel = "beta"
