name = "Auto Ore Dictionary Converter"
filename = "autooredictconv-1.12-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2606/596/autooredictconv-1.12-1.0.1.jar"
hash-format = "murmur2"
hash = "3421504745"

[update]
[update.curseforge]
file-id = 2606596
project-id = 232650
release-channel = "beta"
