name = "Avaritia's Complement"
filename = "Avaritia's Complement-1.12.2-1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2997/23/Avaritia's Complement-1.12.2-1.4.jar"
hash-format = "murmur2"
hash = "4073557974"

[update]
[update.curseforge]
file-id = 2997023
project-id = 323553
release-channel = "beta"
