name = "Avaritia Furnace"
filename = "Avaritia_furnace-1.0.0-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3097/230/Avaritia_furnace-1.0.0-1.12.2.jar"
hash-format = "murmur2"
hash = "1674771689"

[update]
[update.curseforge]
file-id = 3097230
project-id = 416599
release-channel = "beta"
