name = "Better Combat Rebirth"
filename = "BetterCombat-1.12.2-1.5.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2601/52/BetterCombat-1.12.2-1.5.6.jar"
hash-format = "murmur2"
hash = "3788301352"

[update]
[update.curseforge]
file-id = 2601052
project-id = 300100
release-channel = "beta"
