name = "bspkrsCore Updated"
filename = "[1.12]bspkrsCore-universal-7.6.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2722/821/[1.12]bspkrsCore-universal-7.6.0.1.jar"
hash-format = "murmur2"
hash = "2663019083"

[update]
[update.curseforge]
file-id = 2722821
project-id = 323993
release-channel = "beta"
