name = "Carrots Library [FORGE]"
filename = "carrotslib-mc1.12.2-1.0.0b1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2660/247/carrotslib-mc1.12.2-1.0.0b1.jar"
hash-format = "murmur2"
hash = "384680967"

[update]
[update.curseforge]
file-id = 2660247
project-id = 311327
release-channel = "beta"
