name = "Charset Lib"
filename = "Charset-Lib-0.5.6.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/682/Charset-Lib-0.5.6.5.jar"
hash-format = "murmur2"
hash = "2173990858"

[update]
[update.curseforge]
file-id = 3066682
project-id = 284523
release-channel = "beta"
