name = "CreativeCore"
filename = "CreativeCore_v1.10.34_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3097/498/CreativeCore_v1.10.34_mc1.12.2.jar"
hash-format = "murmur2"
hash = "3367826540"

[update]
[update.curseforge]
file-id = 3097498
project-id = 257814
release-channel = "beta"
