name = "CXLibrary"
filename = "cxlibrary-1.12.1-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2463/886/cxlibrary-1.12.1-1.6.1.jar"
hash-format = "murmur2"
hash = "434298282"

[update]
[update.curseforge]
file-id = 2463886
project-id = 244023
release-channel = "beta"
