name = "Effortless Building"
filename = "effortlessbuilding-1.12.2-2.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2847/346/effortlessbuilding-1.12.2-2.16.jar"
hash-format = "murmur2"
hash = "3623204631"

[update]
[update.curseforge]
file-id = 2847346
project-id = 302113
release-channel = "beta"
