name = "ElecCore"
filename = "ElecCore-1.12.2-1.9.453.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2853/959/ElecCore-1.12.2-1.9.453.jar"
hash-format = "murmur2"
hash = "102104902"

[update]
[update.curseforge]
file-id = 2853959
project-id = 227391
release-channel = "beta"
