name = "Ender IO Base"
filename = "EnderIO-base-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/691/EnderIO-base-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "996666159"

[update]
[update.curseforge]
file-id = 3068691
project-id = 297193
release-channel = "beta"
