name = "Ender IO Conduits"
filename = "EnderIO-conduits-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/693/EnderIO-conduits-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "3645637391"

[update]
[update.curseforge]
file-id = 3068693
project-id = 297197
release-channel = "beta"
