name = "Ender IO RS Conduits"
filename = "EnderIO-conduits-refinedstorage-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/696/EnderIO-conduits-refinedstorage-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "245820507"

[update]
[update.curseforge]
file-id = 3068696
project-id = 297201
release-channel = "beta"
