name = "Ender IO Zoo"
filename = "EnderIO-zoo-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/699/EnderIO-zoo-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "2911796559"

[update]
[update.curseforge]
file-id = 3068699
project-id = 303001
release-channel = "beta"
