name = "Expandable Inventory"
filename = "ExpandableInventory-1.12.2-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2751/939/ExpandableInventory-1.12.2-1.4.0.jar"
hash-format = "murmur2"
hash = "2604776347"

[update]
[update.curseforge]
file-id = 2751939
project-id = 304371
release-channel = "beta"
