name = "Furnace on a Stick"
filename = "furnaceonastick-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2475/930/furnaceonastick-1.0.jar"
hash-format = "murmur2"
hash = "1440472034"

[update]
[update.curseforge]
file-id = 2475930
project-id = 277056
release-channel = "beta"
