name = "Howling Moon"
filename = "howlingmoon-1.12.2-0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2567/452/howlingmoon-1.12.2-0.9.jar"
hash-format = "murmur2"
hash = "3203509934"

[update]
[update.curseforge]
file-id = 2567452
project-id = 236149
release-channel = "beta"
