name = "Immersive Cables"
filename = "ImmersiveCables-1.12.2-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2595/13/ImmersiveCables-1.12.2-1.3.2.jar"
hash-format = "murmur2"
hash = "991598649"

[update]
[update.curseforge]
file-id = 2595013
project-id = 283992
release-channel = "beta"
