name = "Loading Profiler"
filename = "LoadingProfiler-MC1.12-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2432/420/LoadingProfiler-MC1.12-1.3.jar"
hash-format = "murmur2"
hash = "1509490519"

[update]
[update.curseforge]
file-id = 2432420
project-id = 228513
release-channel = "beta"
