name = "Logistics Pipes"
filename = "logisticspipes-0.10.3.40.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2982/930/logisticspipes-0.10.3.40.jar"
hash-format = "murmur2"
hash = "4118797864"

[update]
[update.curseforge]
file-id = 2982930
project-id = 232838
release-channel = "beta"
