name = "Long Fall Boots"
filename = "longfallboots-1.2.1b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2595/728/longfallboots-1.2.1b.jar"
hash-format = "murmur2"
hash = "248361575"

[update]
[update.curseforge]
file-id = 2595728
project-id = 254032
release-channel = "beta"
