name = "MineColonies"
filename = "minecolonies-1.12.2-0.11.841-ALPHA-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2932/783/minecolonies-1.12.2-0.11.841-ALPHA-universal.jar"
hash-format = "murmur2"
hash = "2866255182"

[update]
[update.curseforge]
file-id = 2932783
project-id = 245506
release-channel = "beta"
