name = "Multi Mine"
filename = "MultiMine-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2790/649/MultiMine-1.12.2.jar"
hash-format = "murmur2"
hash = "2010594871"

[update]
[update.curseforge]
file-id = 2790649
project-id = 227887
release-channel = "beta"
