name = "NoFog"
filename = "NoFog-1.12.2b3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2604/160/NoFog-1.12.2b3.jar"
hash-format = "murmur2"
hash = "4113840168"

[update]
[update.curseforge]
file-id = 2604160
project-id = 296468
release-channel = "beta"
