name = "Novam Terram"
filename = "Novam Terram 1.12.2 - 7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2908/447/Novam Terram 1.12.2 - 7.3.jar"
hash-format = "murmur2"
hash = "3230792613"

[update]
[update.curseforge]
file-id = 2908447
project-id = 298802
release-channel = "beta"
