name = "Nukepowered Utils"
filename = "NPUtils-1.12.2-1.3.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2864/415/NPUtils-1.12.2-1.3.21.jar"
hash-format = "murmur2"
hash = "1742229888"

[update]
[update.curseforge]
file-id = 2864415
project-id = 352688
release-channel = "beta"
