name = "Oh The Biomes You'll Go"
filename = "BiomesYouGo1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2833/179/BiomesYouGo1.7.1.jar"
hash-format = "murmur2"
hash = "38524416"

[update]
[update.curseforge]
file-id = 2833179
project-id = 247560
release-channel = "beta"
