name = "Old Swing"
filename = "OldSwing-1.12.2-1.0.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3038/332/OldSwing-1.12.2-1.0.0.0.jar"
hash-format = "murmur2"
hash = "2694805944"

[update]
[update.curseforge]
file-id = 3038332
project-id = 403590
release-channel = "beta"
