name = "Ore Canes Mod"
filename = "Ore Canes Mod (v.1.4.2).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2816/972/Ore Canes Mod (v.1.4.2).jar"
hash-format = "murmur2"
hash = "1672475718"

[update]
[update.curseforge]
file-id = 2816972
project-id = 295675
release-channel = "beta"
