name = "Overloaded Ores"
filename = "Overloaded Ores.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2929/579/Overloaded Ores.jar"
hash-format = "murmur2"
hash = "3083330480"

[update]
[update.curseforge]
file-id = 2929579
project-id = 361238
release-channel = "beta"
