name = "OverPowered Pickaxes Mod"
filename = "OVERPOWERED PICKAXES MOD.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2738/206/OVERPOWERED PICKAXES MOD.jar"
hash-format = "murmur2"
hash = "1977729419"

[update]
[update.curseforge]
file-id = 2738206
project-id = 326824
release-channel = "beta"
