name = "Pipe Goggles"
filename = "PipeMaster-1.0.2-b8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2676/874/PipeMaster-1.0.2-b8.jar"
hash-format = "murmur2"
hash = "843970653"

[update]
[update.curseforge]
file-id = 2676874
project-id = 309607
release-channel = "beta"
