name = "Doomlike Dungeons"
filename = "DoomlikeDungeons-1.13.2-MC1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2905/498/DoomlikeDungeons-1.13.2-MC1.12.2.jar"
hash-format = "murmur2"
hash = "2042535157"

[update]
[update.curseforge]
file-id = 2905498
project-id = 74246
release-channel = "beta"
