name = "Raiders"
filename = "raiders-1.12.2-3.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2739/763/raiders-1.12.2-3.0.9.jar"
hash-format = "murmur2"
hash = "32254356"

[update]
[update.curseforge]
file-id = 2739763
project-id = 262860
release-channel = "beta"
