name = "Recurrent Complex"
filename = "RecurrentComplex-1.4.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2689/602/RecurrentComplex-1.4.8.2.jar"
hash-format = "murmur2"
hash = "2120690174"

[update]
[update.curseforge]
file-id = 2689602
project-id = 223150
release-channel = "beta"
