name = "Refined Avaritia"
filename = "refined_avaritia-1.12.2-2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2680/357/refined_avaritia-1.12.2-2.6.jar"
hash-format = "murmur2"
hash = "4041124196"

[update]
[update.curseforge]
file-id = 2680357
project-id = 269583
release-channel = "beta"
