name = "RFTools Power"
filename = "rftoolspower-1.12-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2704/404/rftoolspower-1.12-1.2.0.jar"
hash-format = "murmur2"
hash = "2353472270"

[update]
[update.curseforge]
file-id = 2704404
project-id = 290209
release-channel = "beta"
