name = "RSInfiniteWireless"
filename = "rsinfinitewireless-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2695/806/rsinfinitewireless-1.2.jar"
hash-format = "murmur2"
hash = "1597884723"

[update]
[update.curseforge]
file-id = 2695806
project-id = 318823
release-channel = "beta"
