name = "Secure EnderStorage"
filename = "Secure EnderStorage-1.12.2-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2954/600/Secure EnderStorage-1.12.2-1.1.0.jar"
hash-format = "murmur2"
hash = "3308189272"

[update]
[update.curseforge]
file-id = 2954600
project-id = 374783
release-channel = "beta"
