name = "SimpleLogic Gates"
filename = "SimpleLogic-Gates-0.5.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2745/283/SimpleLogic-Gates-0.5.6.1.jar"
hash-format = "murmur2"
hash = "4177513263"

[update]
[update.curseforge]
file-id = 2745283
project-id = 289316
release-channel = "beta"
