name = "Solar Panels Reforged"
filename = "SolarPanelsReforged-1.12.2-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2725/884/SolarPanelsReforged-1.12.2-1.0.jar"
hash-format = "murmur2"
hash = "4011532037"

[update]
[update.curseforge]
file-id = 2725884
project-id = 324577
release-channel = "beta"
