name = "Squeedometer"
filename = "Squeedometer-mc1.12.x-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2495/580/Squeedometer-mc1.12.x-1.0.4.jar"
hash-format = "murmur2"
hash = "1531304444"

[update]
[update.curseforge]
file-id = 2495580
project-id = 223359
release-channel = "beta"
