name = "Tails"
filename = "Tails-1.12-1.10.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2445/532/Tails-1.12-1.10.0.jar"
hash-format = "murmur2"
hash = "3286169498"

[update]
[update.curseforge]
file-id = 2445532
project-id = 223584
release-channel = "beta"
