name = "TekTopia"
filename = "tektopia-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2763/46/tektopia-1.1.0.jar"
hash-format = "murmur2"
hash = "2141021463"

[update]
[update.curseforge]
file-id = 2763046
project-id = 333029
release-channel = "beta"
