name = "TrashSlot"
filename = "TrashSlot_1.12.2-8.4.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2722/385/TrashSlot_1.12.2-8.4.10.jar"
hash-format = "murmur2"
hash = "3748135553"

[update]
[update.curseforge]
file-id = 2722385
project-id = 235577
release-channel = "beta"
