name = "Treecapitator Updated"
filename = "[1.12]TreeCapitator-client-1.43.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2722/878/[1.12]TreeCapitator-client-1.43.0.jar"
hash-format = "murmur2"
hash = "463659856"

[update]
[update.curseforge]
file-id = 2722878
project-id = 324007
release-channel = "beta"
