name = "Underground Biomes"
filename = "UndergroundBiomesConstructs-1.12-1.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2925/430/UndergroundBiomesConstructs-1.12-1.3.8.jar"
hash-format = "murmur2"
hash = "3124812282"

[update]
[update.curseforge]
file-id = 2925430
project-id = 293268
release-channel = "beta"
