name = "UniDict"
filename = "UniDict-1.12.2-2.9.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3087/799/UniDict-1.12.2-2.9.8.jar"
hash-format = "murmur2"
hash = "4232827206"

[update]
[update.curseforge]
file-id = 3087799
project-id = 244258
release-channel = "beta"
