name = "Universal Bestiary"
filename = "universalbestiary-1.12.2-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2873/970/universalbestiary-1.12.2-1.3.1.jar"
hash-format = "murmur2"
hash = "3151955294"

[update]
[update.curseforge]
file-id = 2873970
project-id = 311283
release-channel = "beta"
