name = "Wall-Jump! [FORGE]"
filename = "walljump-1.12.2-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2865/90/walljump-1.12.2-1.3.2.jar"
hash-format = "murmur2"
hash = "2388595289"

[update]
[update.curseforge]
file-id = 2865090
project-id = 295319
release-channel = "beta"
