name = "Worley's Caves"
filename = "worleycaves-1.12.2-1.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3038/801/worleycaves-1.12.2-1.5.2.jar"
hash-format = "murmur2"
hash = "4235109984"

[update]
[update.curseforge]
file-id = 3038801
project-id = 299815
release-channel = "beta"
