name = "Xaero's World Map"
filename = "XaerosWorldMap_1.11.0_Forge_1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/324/XaerosWorldMap_1.11.0_Forge_1.12.jar"
hash-format = "murmur2"
hash = "1978696401"

[update]
[update.curseforge]
file-id = 3063324
project-id = 317780
release-channel = "beta"
