name = "A Block of Charcoal"
filename = "A Block of Charcoal-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2574/220/A Block of Charcoal-1.2.jar"
hash-format = "murmur2"
hash = "4170485159"

[update]
[update.curseforge]
file-id = 2574220
project-id = 251079
release-channel = "beta"
