name = "Actually Baubles"
filename = "ActuallyBaubles-1.12-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2459/131/ActuallyBaubles-1.12-1.1.jar"
hash-format = "murmur2"
hash = "4219803846"

[update]
[update.curseforge]
file-id = 2459131
project-id = 273430
release-channel = "beta"
