name = "Advent of Ascension (Nevermine)"
filename = "AoA3-3.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3054/253/AoA3-3.3.6.jar"
hash-format = "murmur2"
hash = "3245904972"

[update]
[update.curseforge]
file-id = 3054253
project-id = 311054
release-channel = "beta"
