name = "Auto Feeder Helmet [FORGE]"
filename = "FeederHelmet-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2845/710/FeederHelmet-1.4.2.jar"
hash-format = "murmur2"
hash = "1314894241"

[update]
[update.curseforge]
file-id = 2845710
project-id = 292257
release-channel = "beta"
