name = "Auto Pickup"
filename = "AutoPickup-1.12-2.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2689/822/AutoPickup-1.12-2.5.1.jar"
hash-format = "murmur2"
hash = "3512925907"

[update]
[update.curseforge]
file-id = 2689822
project-id = 238284
release-channel = "beta"
