name = "Bedrock B Gone"
filename = "BetterBedrock-1.12.2-5.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2790/210/BetterBedrock-1.12.2-5.1.11.jar"
hash-format = "murmur2"
hash = "2083161138"

[update]
[update.curseforge]
file-id = 2790210
project-id = 255053
release-channel = "beta"
