name = "BetterNether"
filename = "betternether-0.1.8.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2859/893/betternether-0.1.8.6.jar"
hash-format = "murmur2"
hash = "1326824199"

[update]
[update.curseforge]
file-id = 2859893
project-id = 311377
release-channel = "beta"
