name = "Better Sprinting"
filename = "BetterSprinting-1.12.2-v3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2742/508/BetterSprinting-1.12.2-v3.0.1.jar"
hash-format = "murmur2"
hash = "3486345777"

[update]
[update.curseforge]
file-id = 2742508
project-id = 227409
release-channel = "beta"
