name = "Carry On"
filename = "carryon-1.12.2-1.12.3.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3004/475/carryon-1.12.2-1.12.3.15.jar"
hash-format = "murmur2"
hash = "2439152564"

[update]
[update.curseforge]
file-id = 3004475
project-id = 274259
release-channel = "beta"
