name = "Castle Dungeons"
filename = "castle_dungeons-1.3-1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3023/264/castle_dungeons-1.3-1.12.2.jar"
hash-format = "murmur2"
hash = "3666522248"

[update]
[update.curseforge]
file-id = 3023264
project-id = 399213
release-channel = "beta"
