name = "Chickens"
filename = "chickens-6.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2545/467/chickens-6.1.0.jar"
hash-format = "murmur2"
hash = "1134844635"

[update]
[update.curseforge]
file-id = 2545467
project-id = 241941
release-channel = "beta"
