name = "Default World Generator (port)"
filename = "DefaultWorldGenerator-port-1.12-2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2499/252/DefaultWorldGenerator-port-1.12-2.3.jar"
hash-format = "murmur2"
hash = "2577627143"

[update]
[update.curseforge]
file-id = 2499252
project-id = 241140
release-channel = "beta"
