name = "Default LAN Port"
filename = "Default LAN Port-1.0 1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2574/322/Default LAN Port-1.0 1.12.2.jar"
hash-format = "murmur2"
hash = "1105761241"

[update]
[update.curseforge]
file-id = 2574322
project-id = 296306
release-channel = "beta"
