name = "Elenai Dodge"
filename = "ElenaiDodge-1.12.2-1.12.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/977/ElenaiDodge-1.12.2-1.12.0.jar"
hash-format = "murmur2"
hash = "638780874"

[update]
[update.curseforge]
file-id = 3063977
project-id = 373104
release-channel = "beta"
