name = "Ender IO Endergy"
filename = "EnderIO-endergy-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/700/EnderIO-endergy-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "94036208"

[update]
[update.curseforge]
file-id = 3068700
project-id = 304346
release-channel = "beta"
