name = "Ender IO Machines"
filename = "EnderIO-machines-1.12.2-5.2.61.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/692/EnderIO-machines-1.12.2-5.2.61.jar"
hash-format = "murmur2"
hash = "1449409394"

[update]
[update.curseforge]
file-id = 3068692
project-id = 297196
release-channel = "beta"
