name = "Fullscreen Windowed (Borderless) for Minecraft"
filename = "FullscreenWindowed-1.12-1.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2456/7/FullscreenWindowed-1.12-1.6.0.jar"
hash-format = "murmur2"
hash = "1002938307"

[update]
[update.curseforge]
file-id = 2456007
project-id = 227441
release-channel = "beta"
