name = "Furnace Overhaul"
filename = "furnaceoverhaul-1.12.2-2.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2910/813/furnaceoverhaul-1.12.2-2.2.2.jar"
hash-format = "murmur2"
hash = "780199672"

[update]
[update.curseforge]
file-id = 2910813
project-id = 262742
release-channel = "beta"
