name = "GregTech Community Edition"
filename = "gregtech-1.12.2-1.10.5.582.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3107/885/gregtech-1.12.2-1.10.5.582.jar"
hash-format = "murmur2"
hash = "2947452828"

[update]
[update.curseforge]
file-id = 3107885
project-id = 293327
release-channel = "beta"
