name = "Guidebook"
filename = "Guidebook-1.12.2-2.9.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/594/Guidebook-1.12.2-2.9.5.jar"
hash-format = "murmur2"
hash = "1099974475"

[update]
[update.curseforge]
file-id = 2989594
project-id = 253874
release-channel = "beta"
