name = "Headcrumbs"
filename = "Headcrumbs-1.12.2-2.0.5.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2645/20/Headcrumbs-1.12.2-2.0.5.17.jar"
hash-format = "murmur2"
hash = "1013802123"

[update]
[update.curseforge]
file-id = 2645020
project-id = 222838
release-channel = "beta"
