name = "Huds - Armor Status & Damage Indicators"
filename = "Huds-1.12.2-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2854/134/Huds-1.12.2-1.0.6.jar"
hash-format = "murmur2"
hash = "834037108"

[update]
[update.curseforge]
file-id = 2854134
project-id = 265640
release-channel = "beta"
