name = "Infinite Water Source"
filename = "infinitewatersource-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2711/928/infinitewatersource-1.1.jar"
hash-format = "murmur2"
hash = "2431621218"

[update]
[update.curseforge]
file-id = 2711928
project-id = 321795
release-channel = "beta"
