name = "Infinity Item Editor"
filename = "Infinity-0.14.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2992/997/Infinity-0.14.2.jar"
hash-format = "murmur2"
hash = "78418827"

[update]
[update.curseforge]
file-id = 2992997
project-id = 290958
release-channel = "beta"
