name = "Instrumental Mobs"
filename = "Instrumental-Mobs-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3096/365/Instrumental-Mobs-1.2.1.jar"
hash-format = "murmur2"
hash = "703033535"

[update]
[update.curseforge]
file-id = 3096365
project-id = 299602
release-channel = "beta"
