name = "ItemPhysic Full"
filename = "ItemPhysic_Full_1.4.34_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2959/712/ItemPhysic_Full_1.4.34_mc1.12.2.jar"
hash-format = "murmur2"
hash = "1365242104"

[update]
[update.curseforge]
file-id = 2959712
project-id = 258587
release-channel = "beta"
