name = "LagGoggles"
filename = "LagGoggles-FAT-1.12.2-4.11-92.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2901/775/LagGoggles-FAT-1.12.2-4.11-92.jar"
hash-format = "murmur2"
hash = "3464936186"

[update]
[update.curseforge]
file-id = 2901775
project-id = 283525
release-channel = "beta"
