name = "MattDahEpic Core (MDECore)"
filename = "mdecore-1.12-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2617/399/mdecore-1.12-1.1.jar"
hash-format = "murmur2"
hash = "3314553653"

[update]
[update.curseforge]
file-id = 2617399
project-id = 229595
release-channel = "beta"
