name = "Mobs Properties Randomness"
filename = "MobsPropertiesRandomness-2.3.3-mc1.12.x.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2823/889/MobsPropertiesRandomness-2.3.3-mc1.12.x.jar"
hash-format = "murmur2"
hash = "4098719584"

[update]
[update.curseforge]
file-id = 2823889
project-id = 285012
release-channel = "beta"
