name = "More Buckets"
filename = "MoreBuckets-1.12.2-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2695/556/MoreBuckets-1.12.2-1.0.4.jar"
hash-format = "murmur2"
hash = "3399440960"

[update]
[update.curseforge]
file-id = 2695556
project-id = 298760
release-channel = "beta"
