name = "More Furnaces"
filename = "MoreFurnaces-1.12.2-1.10.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2627/678/MoreFurnaces-1.12.2-1.10.6.jar"
hash-format = "murmur2"
hash = "1243940434"

[update]
[update.curseforge]
file-id = 2627678
project-id = 78320
release-channel = "beta"
