name = "No Mob Spawning on Trees"
filename = "NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2563/292/NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar"
hash-format = "murmur2"
hash = "4281345704"

[update]
[update.curseforge]
file-id = 2563292
project-id = 226779
release-channel = "beta"
