name = "NoDamI (No Damage Immunity)"
filename = "nodami-1.12.2-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2969/453/nodami-1.12.2-1.3.1.jar"
hash-format = "murmur2"
hash = "2328785542"

[update]
[update.curseforge]
file-id = 2969453
project-id = 267721
release-channel = "beta"
