name = "Old Combat Mechanics"
filename = "OldCombat-1.12.2-v1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2685/361/OldCombat-1.12.2-v1.0.0.jar"
hash-format = "murmur2"
hash = "589180206"

[update]
[update.curseforge]
file-id = 2685361
project-id = 317035
release-channel = "beta"
