name = "OMLib"
filename = "omlib-1.12.2-3.2.0-256.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3086/478/omlib-1.12.2-3.2.0-256.jar"
hash-format = "murmur2"
hash = "4085419272"

[update]
[update.curseforge]
file-id = 3086478
project-id = 254334
release-channel = "beta"
