name = "OpenScreens"
filename = "openscreens-1.12.2-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2754/959/openscreens-1.12.2-1.0.1.jar"
hash-format = "murmur2"
hash = "3857146311"

[update]
[update.curseforge]
file-id = 2754959
project-id = 325357
release-channel = "beta"
