name = "Ore Sheep Mod"
filename = "1.12.2-OreSheepMod-v4.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2545/963/1.12.2-OreSheepMod-v4.0.3.jar"
hash-format = "murmur2"
hash = "1769965691"

[update]
[update.curseforge]
file-id = 2545963
project-id = 226876
release-channel = "beta"
