name = "Overpowered Mending"
filename = "OverpoweredMending-1.12.2-1.0.1+8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2810/994/OverpoweredMending-1.12.2-1.0.1+8.jar"
hash-format = "murmur2"
hash = "4012386249"

[update]
[update.curseforge]
file-id = 2810994
project-id = 344973
release-channel = "beta"
