name = "Overloaded"
filename = "Overloaded-1.12.2-0.0.59.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2875/265/Overloaded-1.12.2-0.0.59.jar"
hash-format = "murmur2"
hash = "401018132"

[update]
[update.curseforge]
file-id = 2875265
project-id = 264601
release-channel = "beta"
