name = "Performant"
filename = "performant-1.12.2-1.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2939/52/performant-1.12.2-1.10.jar"
hash-format = "murmur2"
hash = "3494707198"

[update]
[update.curseforge]
file-id = 2939052
project-id = 354143
release-channel = "beta"
