name = "Project: Vibrant Journeys"
filename = "ProjectVibrantJourneys-1.12.2-1.6.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2775/566/ProjectVibrantJourneys-1.12.2-1.6.4.jar"
hash-format = "murmur2"
hash = "125016202"

[update]
[update.curseforge]
file-id = 2775566
project-id = 300297
release-channel = "beta"
