name = "pvpToggle"
filename = "pvpToggle-1.12.1-2.0.38-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2516/106/pvpToggle-1.12.1-2.0.38-universal.jar"
hash-format = "murmur2"
hash = "3428331221"

[update]
[update.curseforge]
file-id = 2516106
project-id = 223394
release-channel = "beta"
