name = "Reborn Storage"
filename = "RebornStorage-1.12.2-3.3.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2833/871/RebornStorage-1.12.2-3.3.4.1.jar"
hash-format = "murmur2"
hash = "3685526158"

[update]
[update.curseforge]
file-id = 2833871
project-id = 256662
release-channel = "beta"
