name = "Redstone Paste"
filename = "redstonepaste-mc1.12-1.7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2477/676/redstonepaste-mc1.12-1.7.5.jar"
hash-format = "murmur2"
hash = "1862503917"

[update]
[update.curseforge]
file-id = 2477676
project-id = 67508
release-channel = "beta"
