name = "Resynth - Growable Ores & Resources"
filename = "resynth-1.3.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2825/901/resynth-1.3.9.jar"
hash-format = "murmur2"
hash = "3130650386"

[update]
[update.curseforge]
file-id = 2825901
project-id = 303846
release-channel = "beta"
