name = "Rocket Boots"
filename = "RocketBoots0.2.6-1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3027/921/RocketBoots0.2.6-1.12.jar"
hash-format = "murmur2"
hash = "2008357014"

[update]
[update.curseforge]
file-id = 3027921
project-id = 393967
release-channel = "beta"
