name = "Roguelike Dungeons - Fnar Edition"
filename = "RoguelikeDungeonsFnarEdition-1.12.2-2.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3048/689/RoguelikeDungeonsFnarEdition-1.12.2-2.1.4.jar"
hash-format = "murmur2"
hash = "2424614080"

[update]
[update.curseforge]
file-id = 3048689
project-id = 373157
release-channel = "beta"
