name = "Server Tick Monitor"
filename = "ServerTickMonitor-1.12-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2444/248/ServerTickMonitor-1.12-3.0.0.jar"
hash-format = "murmur2"
hash = "2420657517"

[update]
[update.curseforge]
file-id = 2444248
project-id = 252319
release-channel = "beta"
