name = "Simple Ore Generation"
filename = "SimpleOreGeneration-4.3.4 mc 1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2701/27/SimpleOreGeneration-4.3.4 mc 1.12.2.jar"
hash-format = "murmur2"
hash = "555552795"

[update]
[update.curseforge]
file-id = 2701027
project-id = 244249
release-channel = "beta"
