name = "Simple Generators"
filename = "simplegenerators-1.12.2-2.0.20.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2694/397/simplegenerators-1.12.2-2.0.20.2.jar"
hash-format = "murmur2"
hash = "3444467833"

[update]
[update.curseforge]
file-id = 2694397
project-id = 246010
release-channel = "beta"
