name = "Special AI"
filename = "specialai-1.1.0_for_mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2686/991/specialai-1.1.0_for_mc1.12.2.jar"
hash-format = "murmur2"
hash = "3563140782"

[update]
[update.curseforge]
file-id = 2686991
project-id = 224301
release-channel = "beta"
