name = "Storage Tech"
filename = "StorageTech R6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2671/48/StorageTech R6.0.jar"
hash-format = "murmur2"
hash = "507037579"

[update]
[update.curseforge]
file-id = 2671048
project-id = 274033
release-channel = "beta"
