name = "TekTopia Information"
filename = "TektopiaInformation-1.12.2-1.1.0-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2795/709/TektopiaInformation-1.12.2-1.1.0-1.4.0.jar"
hash-format = "murmur2"
hash = "1079814017"

[update]
[update.curseforge]
file-id = 2795709
project-id = 340977
release-channel = "beta"
