name = "Tick Dynamic"
filename = "TickDynamic-1.12.2-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2737/879/TickDynamic-1.12.2-1.0.2.jar"
hash-format = "murmur2"
hash = "793764421"

[update]
[update.curseforge]
file-id = 2737879
project-id = 269359
release-channel = "beta"
