name = "Xaero's Minimap"
filename = "Xaeros_Minimap_20.27.2_Forge_1.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3103/764/Xaeros_Minimap_20.27.2_Forge_1.12.jar"
hash-format = "murmur2"
hash = "4009467711"

[update]
[update.curseforge]
file-id = 3103764
project-id = 263420
release-channel = "beta"
